support gn/pad
openppl-public/ppl.pmx pull request #75
Opened 2024-05-07 09:39 UTC by Jzz24

support gn/pad

2024-05-07 10:24 UTC, Alcanderian requested changes

2024-05-07 10:24 UTC, Alcanderian commented on torch_function/__init__.py
> +from .Pad import padding
padding?

2024-05-07 10:24 UTC, Alcanderian commented on torch_function/Pad.py
> +def padding(input: torch.Tensor, pad: Sequence[Union[int, torch.SymInt]],
不能用pad么

2024-05-07 10:24 UTC, Alcanderian commented on torch_function/Pad.py
> +                mode: str='constant', value: float=0.):
value是不是得是一个tensor（scalar就行）

2024-05-07 10:24 UTC, Alcanderian commented on docs/operators/Pad.md
> +### `mode`: str
mode是个attr，放到attr里，按照attr的格式改一下

2024-05-08 03:55 UTC, Jzz24 commented on torch_function/Pad.py
> +def padding(input: torch.Tensor, pad: Sequence[Union[int, torch.SymInt]],
可以的，主要line23 函数里面有一个pad参数，函数名字和参数名一样，会出问题，容我修改修改

2024-05-09 17:28 UTC, merged