support int4 quantization CPlinear
openppl-public/ppl.pmx pull request #84
Opened 2024-06-19 07:00 UTC by Jzz24

2024-06-21 13:12 UTC, Alcanderian requested changes

2024-06-21 13:12 UTC, Alcanderian commented on torch_function/ModelQuantUtils.py
> +def pseudo_quantize_tensor(w, n_bit=4, zero_point=True, group_size=-1):
pseudo_quantize_tensor 改成 pseudo_quantize_linear_weight？

2024-06-21 13:12 UTC, Alcanderian commented on torch_function/ModelQuantUtils.py
> +class Int4_QuantUtils():
下划线去掉吧

2024-06-21 13:12 UTC, Alcanderian commented on torch_function/WoquColumnParallelLinear.py
> +from ModelQuantUtils import Int4_QuantUtils
文件名改WeightOnlyQuantUtils？

2024-06-21 13:12 UTC, Alcanderian commented on torch_function/WoquColumnParallelLinear.py
> +        g, X: torch.Value, W: torch.Value, B: torch.Value, proc_group: torch.Value,
proc_group这个参数，放到所有tensor后面

然后文档里面的参数顺序不是这个
是
W, X, Scale, ZeroPoint, B

具体参考
https://github.com/openppl-public/ppl.pmx/blob/master/docs/operators/WoquColumnParallelLinear.md

2024-06-24 06:21 UTC, Jzz24 commented on torch_function/WoquColumnParallelLinear.py
> +        g, X: torch.Value, W: torch.Value, B: torch.Value, proc_group: torch.Value,
ok

2024-07-01 09:20 UTC, merged